settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Vinet-IX-CPT # unique identifier
    name: CPT Vinet
    description: '' # default=empty
    url: 'https://160.226.128.6:82' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    linkable: false # allows the title to be a link, default=true

  - id: UNIFI1
    name: unifi1.vinethosting.org
    description: 'Unifi Hosting.'
    url: 'https://unifi1.vinethosting.org:8443'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: VINET-WEBSITE
    name: The Vinet Website
    url: 'https://www.vinet.co.za/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true


    
  - id: VINET-SPLYNX
    name: The Vinet Customer Portal
    url: 'https://splynx.vinet.co.za/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

